In [1]:
import numpy as np

In [15]:
print(arr.shape)

(2, 3)


In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b=np.array([[1,2,3],[4,5,7]])
print(b)

[[1 2 3]
 [4 5 7]]


In [4]:
c=np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
arr=np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
arr=np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
print(arr.ndim)


2


In [18]:
print(arr.size)

6


In [19]:
print(arr.dtype)

int64


In [20]:
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[2])

10
30


In [21]:
print(arr[-1])

40


In [23]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [24]:
arr=np.array([10,20,30,40,50,60])
print(arr[1:4])

[20 30 40]


In [25]:
print(arr[:3])

[10 20 30]


In [26]:
print(arr[:2])

[10 20]


In [29]:
arr=np.arange(1,13)
new_arr=arr.reshape(3,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
arr=np.arange(1,13)
new_arr=arr.reshape(2,2,3)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [32]:
arr=np.array([[1,2],
              [3,4]])
print(arr.flatten())

[1 2 3 4]
